// Mocks generated by Mockito 5.4.5 from annotations
// in flower_app/test/features/profile/presentation/cubit/profile_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:either_dart/either.dart' as _i4;
import 'package:flower_app/core/error_handling/exceptions/api_exception.dart'
    as _i8;
import 'package:flower_app/features/auth/data/datasource/local_data_source/auth_local_data_source_contract.dart'
    as _i19;
import 'package:flower_app/features/checkout/domain/entities/address.dart'
    as _i11;
import 'package:flower_app/features/profile/data/models/reset_password/request/profile_reset_password_request.dart'
    as _i18;
import 'package:flower_app/features/profile/data/models/reset_password/response/profile_reset_password_response.dart'
    as _i17;
import 'package:flower_app/features/profile/data/models/update_profile_data/update_profile_request.dart'
    as _i9;
import 'package:flower_app/features/profile/domain/entities/user_data.dart'
    as _i5;
import 'package:flower_app/features/profile/domain/entities/user_orders/user_orders_entitiy.dart'
    as _i14;
import 'package:flower_app/features/profile/domain/usecases/delete_address_usecase.dart'
    as _i12;
import 'package:flower_app/features/profile/domain/usecases/edit_profile_use_case.dart'
    as _i7;
import 'package:flower_app/features/profile/domain/usecases/get_user_data_use_case.dart'
    as _i2;
import 'package:flower_app/features/profile/domain/usecases/get_user_oders_use_case.dart'
    as _i13;
import 'package:flower_app/features/profile/domain/usecases/logout_use_case.dart'
    as _i15;
import 'package:flower_app/features/profile/domain/usecases/reset_password_use_case.dart'
    as _i16;
import 'package:flower_app/features/profile/domain/usecases/update_address_usecase.dart'
    as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GetUserDataUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetUserDataUseCase extends _i1.Mock
    implements _i2.GetUserDataUseCase {
  MockGetUserDataUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<Exception, _i5.UserData>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i3.Future<_i4.Either<Exception, _i5.UserData>>.value(
            _i6.dummyValue<_i4.Either<Exception, _i5.UserData>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Either<Exception, _i5.UserData>>);
}

/// A class which mocks [EditProfileUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockEditProfileUseCase extends _i1.Mock
    implements _i7.EditProfileUseCase {
  MockEditProfileUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i8.ApiException, void>> call(
          _i9.UpdateProfileRequest? updateProfileRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [updateProfileRequest],
        ),
        returnValue: _i3.Future<_i4.Either<_i8.ApiException, void>>.value(
            _i6.dummyValue<_i4.Either<_i8.ApiException, void>>(
          this,
          Invocation.method(
            #call,
            [updateProfileRequest],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i8.ApiException, void>>);
}

/// A class which mocks [UpdateAddressUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateAddressUsecase extends _i1.Mock
    implements _i10.UpdateAddressUsecase {
  MockUpdateAddressUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i11.Address>> call(_i11.Address? address) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [address],
        ),
        returnValue: _i3.Future<List<_i11.Address>>.value(<_i11.Address>[]),
      ) as _i3.Future<List<_i11.Address>>);
}

/// A class which mocks [DeleteAddressUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteAddressUsecase extends _i1.Mock
    implements _i12.DeleteAddressUsecase {
  MockDeleteAddressUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> call(String? id) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [GetUserOdersUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetUserOdersUseCase extends _i1.Mock
    implements _i13.GetUserOdersUseCase {
  MockGetUserOdersUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i8.ApiException, List<_i14.UserOrdersEntitiy>>>
      call() => (super.noSuchMethod(
            Invocation.method(
              #call,
              [],
            ),
            returnValue: _i3.Future<
                _i4.Either<_i8.ApiException,
                    List<_i14.UserOrdersEntitiy>>>.value(_i6.dummyValue<
                _i4.Either<_i8.ApiException, List<_i14.UserOrdersEntitiy>>>(
              this,
              Invocation.method(
                #call,
                [],
              ),
            )),
          ) as _i3.Future<
              _i4.Either<_i8.ApiException, List<_i14.UserOrdersEntitiy>>>);
}

/// A class which mocks [LogoutUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogoutUseCase extends _i1.Mock implements _i15.LogoutUseCase {
  MockLogoutUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<Exception, void>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i3.Future<_i4.Either<Exception, void>>.value(
            _i6.dummyValue<_i4.Either<Exception, void>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Either<Exception, void>>);
}

/// A class which mocks [ResetPasswordUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockResetPasswordUseCase extends _i1.Mock
    implements _i16.ResetPasswordUseCase {
  MockResetPasswordUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i8.ApiException, _i17.ProfileResetPasswordResponse>>
      call(_i18.ProfileResetPasswordRequest? request) => (super.noSuchMethod(
            Invocation.method(
              #call,
              [request],
            ),
            returnValue: _i3.Future<
                _i4.Either<_i8.ApiException,
                    _i17.ProfileResetPasswordResponse>>.value(_i6.dummyValue<
                _i4
                .Either<_i8.ApiException, _i17.ProfileResetPasswordResponse>>(
              this,
              Invocation.method(
                #call,
                [request],
              ),
            )),
          ) as _i3.Future<
              _i4.Either<_i8.ApiException, _i17.ProfileResetPasswordResponse>>);
}

/// A class which mocks [AuthLocalDataSourceContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalDataSourceContract extends _i1.Mock
    implements _i19.AuthLocalDataSourceContract {
  MockAuthLocalDataSourceContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> cacheToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #cacheToken,
          [token],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String?> getToken() => (super.noSuchMethod(
        Invocation.method(
          #getToken,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> deleteToken() => (super.noSuchMethod(
        Invocation.method(
          #deleteToken,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String?> checkSavedToken() => (super.noSuchMethod(
        Invocation.method(
          #checkSavedToken,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> cacheRememberMe(bool? rememberMe) => (super.noSuchMethod(
        Invocation.method(
          #cacheRememberMe,
          [rememberMe],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  bool getRememberMe() => (super.noSuchMethod(
        Invocation.method(
          #getRememberMe,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<void> deleteRememberMe() => (super.noSuchMethod(
        Invocation.method(
          #deleteRememberMe,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
