// Mocks generated by Mockito 5.4.5 from annotations
// in flower_app/test/features/profile/presentation/pages/user_orders_page/user_orders_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flower_app/features/checkout/domain/entities/address.dart'
    as _i7;
import 'package:flower_app/features/profile/domain/entities/user_data.dart'
    as _i6;
import 'package:flower_app/features/profile/presentation/cubit/profile_cubit.dart'
    as _i3;
import 'package:flutter/material.dart' as _i2;
import 'package:flutter_bloc/flutter_bloc.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeValueNotifier_0<T> extends _i1.SmartFake
    implements _i2.ValueNotifier<T> {
  _FakeValueNotifier_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTextEditingController_1 extends _i1.SmartFake
    implements _i2.TextEditingController {
  _FakeTextEditingController_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGlobalKey_2<T extends _i2.State<_i2.StatefulWidget>>
    extends _i1.SmartFake implements _i2.GlobalKey<T> {
  _FakeGlobalKey_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProfileState_3 extends _i1.SmartFake implements _i3.ProfileState {
  _FakeProfileState_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProfileCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileCubit extends _i1.Mock implements _i3.ProfileCubit {
  MockProfileCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ValueNotifier<bool> get isNotificationEnabled => (super.noSuchMethod(
        Invocation.getter(#isNotificationEnabled),
        returnValue: _FakeValueNotifier_0<bool>(
          this,
          Invocation.getter(#isNotificationEnabled),
        ),
      ) as _i2.ValueNotifier<bool>);

  @override
  _i2.TextEditingController get emailController => (super.noSuchMethod(
        Invocation.getter(#emailController),
        returnValue: _FakeTextEditingController_1(
          this,
          Invocation.getter(#emailController),
        ),
      ) as _i2.TextEditingController);

  @override
  set emailController(_i2.TextEditingController? _emailController) =>
      super.noSuchMethod(
        Invocation.setter(
          #emailController,
          _emailController,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.TextEditingController get passwordController => (super.noSuchMethod(
        Invocation.getter(#passwordController),
        returnValue: _FakeTextEditingController_1(
          this,
          Invocation.getter(#passwordController),
        ),
      ) as _i2.TextEditingController);

  @override
  set passwordController(_i2.TextEditingController? _passwordController) =>
      super.noSuchMethod(
        Invocation.setter(
          #passwordController,
          _passwordController,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.TextEditingController get firstNameController => (super.noSuchMethod(
        Invocation.getter(#firstNameController),
        returnValue: _FakeTextEditingController_1(
          this,
          Invocation.getter(#firstNameController),
        ),
      ) as _i2.TextEditingController);

  @override
  set firstNameController(_i2.TextEditingController? _firstNameController) =>
      super.noSuchMethod(
        Invocation.setter(
          #firstNameController,
          _firstNameController,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.TextEditingController get phoneController => (super.noSuchMethod(
        Invocation.getter(#phoneController),
        returnValue: _FakeTextEditingController_1(
          this,
          Invocation.getter(#phoneController),
        ),
      ) as _i2.TextEditingController);

  @override
  set phoneController(_i2.TextEditingController? _phoneController) =>
      super.noSuchMethod(
        Invocation.setter(
          #phoneController,
          _phoneController,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.TextEditingController get lastNameController => (super.noSuchMethod(
        Invocation.getter(#lastNameController),
        returnValue: _FakeTextEditingController_1(
          this,
          Invocation.getter(#lastNameController),
        ),
      ) as _i2.TextEditingController);

  @override
  set lastNameController(_i2.TextEditingController? _lastNameController) =>
      super.noSuchMethod(
        Invocation.setter(
          #lastNameController,
          _lastNameController,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.GlobalKey<_i2.FormState> get editProfileFormKey => (super.noSuchMethod(
        Invocation.getter(#editProfileFormKey),
        returnValue: _FakeGlobalKey_2<_i2.FormState>(
          this,
          Invocation.getter(#editProfileFormKey),
        ),
      ) as _i2.GlobalKey<_i2.FormState>);

  @override
  String get userGender => (super.noSuchMethod(
        Invocation.getter(#userGender),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#userGender),
        ),
      ) as String);

  @override
  set userGender(String? _userGender) => super.noSuchMethod(
        Invocation.setter(
          #userGender,
          _userGender,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.ProfileState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeProfileState_3(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.ProfileState);

  @override
  _i5.Stream<_i3.ProfileState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i5.Stream<_i3.ProfileState>.empty(),
      ) as _i5.Stream<_i3.ProfileState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> getUserData() => (super.noSuchMethod(
        Invocation.method(
          #getUserData,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void changeNotification() => super.noSuchMethod(
        Invocation.method(
          #changeNotification,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> updateProfileData() => (super.noSuchMethod(
        Invocation.method(
          #updateProfileData,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> profileResetPassword(
    String? currentPassword,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #profileResetPassword,
          [
            currentPassword,
            newPassword,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void initEditProfileData(_i6.UserData? userData) => super.noSuchMethod(
        Invocation.method(
          #initEditProfileData,
          [userData],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void updateResetPasswordFormValidity({
    String? currentPassword,
    String? newPassword,
    String? confirmPassword,
    bool? isValid,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #updateResetPasswordFormValidity,
          [],
          {
            #currentPassword: currentPassword,
            #newPassword: newPassword,
            #confirmPassword: confirmPassword,
            #isValid: isValid,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> onDeleteAddress(String? id) => (super.noSuchMethod(
        Invocation.method(
          #onDeleteAddress,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> onUpdateAddress(_i7.Address? address) => (super.noSuchMethod(
        Invocation.method(
          #onUpdateAddress,
          [address],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> getUserOrders() => (super.noSuchMethod(
        Invocation.method(
          #getUserOrders,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void emit(_i3.ProfileState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i8.Change<_i3.ProfileState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
