// Mocks generated by Mockito 5.4.5 from annotations
// in flower_app/test/features/profile/data/repositories/profile_repo_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:flower_app/features/checkout/domain/entities/address.dart'
    as _i9;
import 'package:flower_app/features/profile/data/datasources/local/profile_local_data_source.dart'
    as _i10;
import 'package:flower_app/features/profile/data/datasources/remote/profile_remote_data_source.dart'
    as _i5;
import 'package:flower_app/features/profile/data/models/get_user_oreders_response/user_orders_response.dart'
    as _i4;
import 'package:flower_app/features/profile/data/models/profile_data_response/user_data_model.dart'
    as _i2;
import 'package:flower_app/features/profile/data/models/reset_password/request/profile_reset_password_request.dart'
    as _i8;
import 'package:flower_app/features/profile/data/models/reset_password/response/profile_reset_password_response.dart'
    as _i3;
import 'package:flower_app/features/profile/data/models/update_profile_data/update_profile_request.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserDataModel_0 extends _i1.SmartFake implements _i2.UserDataModel {
  _FakeUserDataModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProfileResetPasswordResponse_1 extends _i1.SmartFake
    implements _i3.ProfileResetPasswordResponse {
  _FakeProfileResetPasswordResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserOrdersResponse_2 extends _i1.SmartFake
    implements _i4.UserOrdersResponse {
  _FakeUserOrdersResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProfileRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRemoteDataSource extends _i1.Mock
    implements _i5.ProfileRemoteDataSource {
  MockProfileRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.UserDataModel> getUserData() => (super.noSuchMethod(
        Invocation.method(
          #getUserData,
          [],
        ),
        returnValue: _i6.Future<_i2.UserDataModel>.value(_FakeUserDataModel_0(
          this,
          Invocation.method(
            #getUserData,
            [],
          ),
        )),
      ) as _i6.Future<_i2.UserDataModel>);

  @override
  _i6.Future<void> editProfileData(
          _i7.UpdateProfileRequest? updateProfileRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #editProfileData,
          [updateProfileRequest],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i3.ProfileResetPasswordResponse> profileResetPassword(
          _i8.ProfileResetPasswordRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #profileResetPassword,
          [request],
        ),
        returnValue: _i6.Future<_i3.ProfileResetPasswordResponse>.value(
            _FakeProfileResetPasswordResponse_1(
          this,
          Invocation.method(
            #profileResetPassword,
            [request],
          ),
        )),
      ) as _i6.Future<_i3.ProfileResetPasswordResponse>);

  @override
  _i6.Future<void> deleteAddress(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteAddress,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i9.Address>> updateAddress(_i9.Address? address) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAddress,
          [address],
        ),
        returnValue: _i6.Future<List<_i9.Address>>.value(<_i9.Address>[]),
      ) as _i6.Future<List<_i9.Address>>);

  @override
  _i6.Future<_i4.UserOrdersResponse> getUserOrders() => (super.noSuchMethod(
        Invocation.method(
          #getUserOrders,
          [],
        ),
        returnValue:
            _i6.Future<_i4.UserOrdersResponse>.value(_FakeUserOrdersResponse_2(
          this,
          Invocation.method(
            #getUserOrders,
            [],
          ),
        )),
      ) as _i6.Future<_i4.UserOrdersResponse>);
}

/// A class which mocks [ProfileLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileLocalDataSource extends _i1.Mock
    implements _i10.ProfileLocalDataSource {
  MockProfileLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> deleteToken() => (super.noSuchMethod(
        Invocation.method(
          #deleteToken,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}
