// Mocks generated by Mockito 5.4.5 from annotations
// in flower_app/test/features/home/presentation/cubit/home_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:either_dart/either.dart' as _i5;
import 'package:flower_app/core/error_handling/exceptions/api_exception.dart'
    as _i6;
import 'package:flower_app/core/services/location_service.dart' as _i9;
import 'package:flower_app/features/home/domain/entities/home_entity.dart'
    as _i7;
import 'package:flower_app/features/home/domain/use_case/home_use_case.dart'
    as _i3;
import 'package:geolocator/geolocator.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePosition_0 extends _i1.SmartFake implements _i2.Position {
  _FakePosition_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetHomeDataUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetHomeDataUseCase extends _i1.Mock
    implements _i3.GetHomeDataUseCase {
  MockGetHomeDataUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.Either<_i6.ApiException, _i7.HomeEntity>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue:
            _i4.Future<_i5.Either<_i6.ApiException, _i7.HomeEntity>>.value(
                _i8.dummyValue<_i5.Either<_i6.ApiException, _i7.HomeEntity>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.ApiException, _i7.HomeEntity>>);
}

/// A class which mocks [LocationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationService extends _i1.Mock implements _i9.LocationService {
  MockLocationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Position> getCurrentPosition() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentPosition,
          [],
        ),
        returnValue: _i4.Future<_i2.Position>.value(_FakePosition_0(
          this,
          Invocation.method(
            #getCurrentPosition,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Position>);

  @override
  _i4.Future<String> getAddressFromCoordinates(
    double? lat,
    double? lng,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAddressFromCoordinates,
          [
            lat,
            lng,
          ],
        ),
        returnValue: _i4.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #getAddressFromCoordinates,
            [
              lat,
              lng,
            ],
          ),
        )),
      ) as _i4.Future<String>);
}
