// Mocks generated by Mockito 5.4.5 from annotations
// in flower_app/test/features/home/domain/usecase/home_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:either_dart/either.dart' as _i4;
import 'package:flower_app/core/error_handling/exceptions/api_exception.dart'
    as _i5;
import 'package:flower_app/features/home/domain/entities/home_entity.dart'
    as _i6;
import 'package:flower_app/features/home/domain/repo/home_repository_contract.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [HomeRepositoryContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRepositoryContract extends _i1.Mock
    implements _i2.HomeRepositoryContract {
  MockHomeRepositoryContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.ApiException, _i6.HomeEntity>> getHomeData() =>
      (super.noSuchMethod(
        Invocation.method(
          #getHomeData,
          [],
        ),
        returnValue:
            _i3.Future<_i4.Either<_i5.ApiException, _i6.HomeEntity>>.value(
                _i7.dummyValue<_i4.Either<_i5.ApiException, _i6.HomeEntity>>(
          this,
          Invocation.method(
            #getHomeData,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.ApiException, _i6.HomeEntity>>);
}
