// Mocks generated by Mockito 5.4.5 from annotations
// in flower_app/test/features/profile/domain/usecases/get_user_oders_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:either_dart/either.dart' as _i4;
import 'package:flower_app/core/error_handling/exceptions/api_exception.dart'
    as _i7;
import 'package:flower_app/features/checkout/domain/entities/address.dart'
    as _i11;
import 'package:flower_app/features/profile/data/models/reset_password/request/profile_reset_password_request.dart'
    as _i10;
import 'package:flower_app/features/profile/data/models/reset_password/response/profile_reset_password_response.dart'
    as _i9;
import 'package:flower_app/features/profile/data/models/update_profile_data/update_profile_request.dart'
    as _i8;
import 'package:flower_app/features/profile/domain/entities/user_data.dart'
    as _i5;
import 'package:flower_app/features/profile/domain/entities/user_orders/user_orders_entitiy.dart'
    as _i12;
import 'package:flower_app/features/profile/domain/repositories/profile_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepository extends _i1.Mock implements _i2.ProfileRepository {
  MockProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<Exception, _i5.UserData>> getUserData() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserData,
          [],
        ),
        returnValue: _i3.Future<_i4.Either<Exception, _i5.UserData>>.value(
            _i6.dummyValue<_i4.Either<Exception, _i5.UserData>>(
          this,
          Invocation.method(
            #getUserData,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Either<Exception, _i5.UserData>>);

  @override
  _i3.Future<_i4.Either<_i7.ApiException, void>> editUserProfileData(
          _i8.UpdateProfileRequest? updateProfileRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #editUserProfileData,
          [updateProfileRequest],
        ),
        returnValue: _i3.Future<_i4.Either<_i7.ApiException, void>>.value(
            _i6.dummyValue<_i4.Either<_i7.ApiException, void>>(
          this,
          Invocation.method(
            #editUserProfileData,
            [updateProfileRequest],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i7.ApiException, void>>);

  @override
  _i3.Future<_i4.Either<Exception, void>> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i3.Future<_i4.Either<Exception, void>>.value(
            _i6.dummyValue<_i4.Either<Exception, void>>(
          this,
          Invocation.method(
            #logout,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Either<Exception, void>>);

  @override
  _i3.Future<_i4.Either<_i7.ApiException, _i9.ProfileResetPasswordResponse>>
      profileResetPassword(_i10.ProfileResetPasswordRequest? request) =>
          (super.noSuchMethod(
            Invocation.method(
              #profileResetPassword,
              [request],
            ),
            returnValue: _i3.Future<
                _i4.Either<_i7.ApiException,
                    _i9.ProfileResetPasswordResponse>>.value(_i6.dummyValue<
                _i4.Either<_i7.ApiException, _i9.ProfileResetPasswordResponse>>(
              this,
              Invocation.method(
                #profileResetPassword,
                [request],
              ),
            )),
          ) as _i3.Future<
              _i4.Either<_i7.ApiException, _i9.ProfileResetPasswordResponse>>);

  @override
  _i3.Future<List<_i11.Address>> updateAddress(_i11.Address? address) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAddress,
          [address],
        ),
        returnValue: _i3.Future<List<_i11.Address>>.value(<_i11.Address>[]),
      ) as _i3.Future<List<_i11.Address>>);

  @override
  _i3.Future<void> deleteAddress(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteAddress,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i4.Either<_i7.ApiException, List<_i12.UserOrdersEntitiy>>>
      getUserOrders() => (super.noSuchMethod(
            Invocation.method(
              #getUserOrders,
              [],
            ),
            returnValue: _i3.Future<
                _i4.Either<_i7.ApiException,
                    List<_i12.UserOrdersEntitiy>>>.value(_i6.dummyValue<
                _i4.Either<_i7.ApiException, List<_i12.UserOrdersEntitiy>>>(
              this,
              Invocation.method(
                #getUserOrders,
                [],
              ),
            )),
          ) as _i3.Future<
              _i4.Either<_i7.ApiException, List<_i12.UserOrdersEntitiy>>>);
}
