// Mocks generated by Mockito 5.4.4 from annotations
// in flower_app/test/helpers/mocks/auth_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i14;

import 'package:either_dart/either.dart' as _i7;
import 'package:flower_app/core/app_data/local_storage/local_storage_client.dart'
    as _i4;
import 'package:flower_app/core/error_handling/exceptions/api_exception.dart'
    as _i10;
import 'package:flower_app/core/widget/dialog_utils.dart' as _i13;
import 'package:flower_app/features/auth/data/datasource/local_data_source/auth_local_data_source_contract.dart'
    as _i12;
import 'package:flower_app/features/auth/data/model/signup_request_model.dart'
    as _i11;
import 'package:flower_app/features/auth/domain/entities/auth_response_entity.dart'
    as _i8;
import 'package:flower_app/features/auth/domain/repo/auth_repo.dart' as _i6;
import 'package:flutter/material.dart' as _i15;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:shared_preferences/shared_preferences.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSharedPreferences_0 extends _i1.SmartFake
    implements _i2.SharedPreferences {
  _FakeSharedPreferences_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFlutterSecureStorage_1 extends _i1.SmartFake
    implements _i3.FlutterSecureStorage {
  _FakeFlutterSecureStorage_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LocalStorageClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalStorageClient extends _i1.Mock
    implements _i4.LocalStorageClient {
  MockLocalStorageClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SharedPreferences get sharedPreferences => (super.noSuchMethod(
        Invocation.getter(#sharedPreferences),
        returnValue: _FakeSharedPreferences_0(
          this,
          Invocation.getter(#sharedPreferences),
        ),
      ) as _i2.SharedPreferences);

  @override
  set sharedPreferences(_i2.SharedPreferences? _sharedPreferences) =>
      super.noSuchMethod(
        Invocation.setter(
          #sharedPreferences,
          _sharedPreferences,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.FlutterSecureStorage get secureStorage => (super.noSuchMethod(
        Invocation.getter(#secureStorage),
        returnValue: _FakeFlutterSecureStorage_1(
          this,
          Invocation.getter(#secureStorage),
        ),
      ) as _i3.FlutterSecureStorage);

  @override
  set secureStorage(_i3.FlutterSecureStorage? _secureStorage) =>
      super.noSuchMethod(
        Invocation.setter(
          #secureStorage,
          _secureStorage,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<bool>? saveData(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(Invocation.method(
        #saveData,
        [
          key,
          value,
        ],
      )) as _i5.Future<bool>?);

  @override
  String? getData(String? key) => (super.noSuchMethod(Invocation.method(
        #getData,
        [key],
      )) as String?);

  @override
  _i5.Future<void> saveSecuredData(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSecuredData,
          [
            key,
            value,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String?> getSecuredData(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getSecuredData,
          [key],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<void>? deleteData(String? key) => (super.noSuchMethod(
        Invocation.method(
          #deleteData,
          [key],
        ),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>?);

  @override
  _i5.Future<void>? deleteSecuredData(String? key) => (super.noSuchMethod(
        Invocation.method(
          #deleteSecuredData,
          [key],
        ),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>?);

  @override
  _i5.Future<void> saveRememberMe(bool? rememberMe) => (super.noSuchMethod(
        Invocation.method(
          #saveRememberMe,
          [rememberMe],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [AuthRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepo extends _i1.Mock implements _i6.AuthRepo {
  MockAuthRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i7.Either<Exception, _i8.AuthResponseEntity>> signIn(
    String? email,
    String? password,
    bool? rememberMe,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [
            email,
            password,
            rememberMe,
          ],
        ),
        returnValue:
            _i5.Future<_i7.Either<Exception, _i8.AuthResponseEntity>>.value(
                _i9.dummyValue<_i7.Either<Exception, _i8.AuthResponseEntity>>(
          this,
          Invocation.method(
            #signIn,
            [
              email,
              password,
              rememberMe,
            ],
          ),
        )),
      ) as _i5.Future<_i7.Either<Exception, _i8.AuthResponseEntity>>);

  @override
  _i5.Future<_i7.Either<_i10.ApiException, void>> signup(
          _i11.SignUpRequestModel? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #signup,
          [request],
        ),
        returnValue: _i5.Future<_i7.Either<_i10.ApiException, void>>.value(
            _i9.dummyValue<_i7.Either<_i10.ApiException, void>>(
          this,
          Invocation.method(
            #signup,
            [request],
          ),
        )),
      ) as _i5.Future<_i7.Either<_i10.ApiException, void>>);

  @override
  _i5.Future<_i7.Either<_i10.ApiException, void>> forgetPassword(
          String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgetPassword,
          [email],
        ),
        returnValue: _i5.Future<_i7.Either<_i10.ApiException, void>>.value(
            _i9.dummyValue<_i7.Either<_i10.ApiException, void>>(
          this,
          Invocation.method(
            #forgetPassword,
            [email],
          ),
        )),
      ) as _i5.Future<_i7.Either<_i10.ApiException, void>>);

  @override
  _i5.Future<_i7.Either<_i10.ApiException, void>> verifyResetCode(
          String? resetCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyResetCode,
          [resetCode],
        ),
        returnValue: _i5.Future<_i7.Either<_i10.ApiException, void>>.value(
            _i9.dummyValue<_i7.Either<_i10.ApiException, void>>(
          this,
          Invocation.method(
            #verifyResetCode,
            [resetCode],
          ),
        )),
      ) as _i5.Future<_i7.Either<_i10.ApiException, void>>);

  @override
  _i5.Future<_i7.Either<_i10.ApiException, void>> resetPassword(
    String? email,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [
            email,
            newPassword,
          ],
        ),
        returnValue: _i5.Future<_i7.Either<_i10.ApiException, void>>.value(
            _i9.dummyValue<_i7.Either<_i10.ApiException, void>>(
          this,
          Invocation.method(
            #resetPassword,
            [
              email,
              newPassword,
            ],
          ),
        )),
      ) as _i5.Future<_i7.Either<_i10.ApiException, void>>);
}

/// A class which mocks [AuthLocalDataSourceContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalDataSourceContract extends _i1.Mock
    implements _i12.AuthLocalDataSourceContract {
  MockAuthLocalDataSourceContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> cacheToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #cacheToken,
          [token],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String?> getToken() => (super.noSuchMethod(
        Invocation.method(
          #getToken,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<void> deleteToken() => (super.noSuchMethod(
        Invocation.method(
          #deleteToken,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String?> checkSavedToken() => (super.noSuchMethod(
        Invocation.method(
          #checkSavedToken,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<void> cacheRememberMe(bool? rememberMe) => (super.noSuchMethod(
        Invocation.method(
          #cacheRememberMe,
          [rememberMe],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  bool getRememberMe() => (super.noSuchMethod(
        Invocation.method(
          #getRememberMe,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> deleteRememberMe() => (super.noSuchMethod(
        Invocation.method(
          #deleteRememberMe,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [DialogUtils].
///
/// See the documentation for Mockito's code generation for more information.
class MockDialogUtils extends _i1.Mock implements _i13.DialogUtils {
  MockDialogUtils() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void showSnackBar({
    required _i14.Color? textColor,
    required String? message,
    required _i15.BuildContext? context,
    Duration? duration = const Duration(seconds: 5),
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #showSnackBar,
          [],
          {
            #textColor: textColor,
            #message: message,
            #context: context,
            #duration: duration,
          },
        ),
        returnValueForMissingStub: null,
      );
}
