name: Firebase App Distribution

on:
  pull_request:
    types: [labeled]
  workflow_dispatch:
    inputs:
      releaseNotes:
        description: 'Release notes for this build'
        required: false
        default: 'Manual build triggered from GitHub Actions'

jobs:
  distribute:
    if: github.event.label.name == 'ReadyForTesting' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.5.3' 
          channel: 'stable'
          dart-sdk: '2.19.0'

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Create Firebase credentials file
        run: echo "$FIREBASE_CREDENTIALS" > firebase-credentials.json
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.shimaa }}

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: '1:998190875190:android:872fced85dc8ff28ecce97'
          serviceCredentialsFile: firebase-credentials.json
          groups: testers
          file: build/app/outputs/flutter-apk/app-release.apk
          releaseNotes: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.releaseNotes || 'PR Deployment' }}
