name: Firebase App Distribution

on:
  pull_request:
    types: [labeled]
  workflow_dispatch:
    inputs:
      releaseNotes:
        description: 'Release notes for this build'
        required: false
        default: 'Manual build triggered from GitHub Actions'

jobs:
  distribute:
    if: github.event.label.name == 'ReadyForTesting' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'
          channel: stable

      - name: Display versions
        run: |
          flutter --version
          dart --version

      - name: Update dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --debug  

      - name: Upload to Firebase App Distribution
        uses: hasretsariyer/firebase-app-distribution-github-action@v1
        with:
          app_id: '1:998190875190:android:872fced85dc8ff28ecce97'
          firebase_token: ${{ secrets.shimaa }}
          app_file: build/app/outputs/flutter-apk/app-debug.apk
          tester_groups: testers
          release_notes: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.releaseNotes || 'PR Deployment' }}
